site_name: Outils linguistiques
site_url: https://zamer12.github.io/outils-linguistique/
repo_url: https://github.com/ZaMeR12/outils-linguistique
repo_name: Outils linguistique
theme:
  icon:
    repo: fontawesome/brands/github 
  name: material
  font:
    text: Parkinsans
    code: JetBrains Mono
  logo: assets/icon-512.png
  favicon: assets/icon-512.png
  palette:
    # Darkmode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode sombre
      primary: deep purple
      accent: purple
    # Lightmode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode clair
      primary: deep purple
      accent: purple
        
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.blocks.caption
  - meta
  - tables

plugins:
  - glightbox
  - search
  - autolinks
  - social

copyright: Copyright ©️ Documentation par ZaMeR12, 2025

extra_css:
  - https://fonts.googleapis.com/css2?family=Parkinsans:wght@400;500;600;700&display=swap
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap
  
extra:
  social:
    - icon: material/github
      link: https://github.com/ZaMeR12/outils-linguistique